version: '3.6'

services:
 mysql:
  image: mysql:5.7
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: 123456
    MYSQL_DATABASE: boot_app
    MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  ports:
    - "3306:3306"
  volumes:
    - ./mysql/init:/docker-entrypoint-initdb.d/
 nginx:
  image: nginx:1.13
  restart: always
  ports: 
    - "80:80"
    - "443:443"
  volumes:
    - ./nginx/conf.d:/etc/nginx/conf.d
 boot1:
  restart: always
  build: ./parsedemo
  working_dir: /parsedemo
  volumes:
    - ./parsedemo:/parsedemo
    - ~/.m2:/root/.m2
  ports:
    - "8080:8080"
  depends_on:
    - mysql
    - nginx 
  command: mvn clean spring-boot:run -Dspring-boot.run.profiles=docker
 
